# Constants and Variables

### What is Tensorflow?

- Developed by Google Brain Team
- Low and high level APIs
- Important change TF version 2

### What is a tensor?

- Generalization of vectors and matrices
- Collection of numbers
- Specific shape

### Defining tensors in TensorFlow

In [11]:
import tensorflow as tf

In [16]:
# 0D Tensor
d0 = tf.ones((1,))
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [17]:
# 1D Tensor
d1 = tf.ones((2,))
d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [22]:
# 2D Tensor
d2 = tf.ones((2, 2))
d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [31]:
# 3D Tensor
d3 = tf.ones((2, 2, 2))
d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [33]:
# convert tensorflow to numpy array
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### Defining constants in TensorFlow

#### A constant is the simplest category of tensor

- Not trainable
- Can have any dimension

In [37]:
from tensorflow import constant

In [40]:
# Define a 2x3 constant
a = constant(5, shape=[2, 3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 5],
       [5, 5, 5]])>

In [46]:
# Define a 2x2 constant
b = constant([1, 2, 3, 4], shape=[2, 2])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### Defining and initializing variables

In [51]:
# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5], dtype=tf.float32)
a0

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [65]:
# Define a constant 
b = tf.constant(3, dtype=tf.float32)
b

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [69]:
#Compute their product 
c0 = tf.multiply(a0, b)
print(c0)
c1 = a0 * b 
c1

tf.Tensor([ 3.  6.  9. 12. 15.], shape=(5,), dtype=float32)


<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15.], dtype=float32)>

# Basic operations

### What is a TensorFlow operation?

- TensorFlow has a model of computation that revolves around the use of graphs
- A TensorFlow graph contains edges and nodes, where the edges are tensors and the 
node are operations

In [72]:
from tensorflow import constant, add

In [ ]:
# Define 0-dimensional tensors
